### ISSUE TITLE
QT Designer vtk plugin: Error: no override found for 'vtkContextDevice2D'.

### ISSUE THREAD

**Issue by tatafarewell** [commontk/CTK#717] opened 2017-05-30 14:57 UTC
Win10/qt5.8/vtk7.1.1/Microsoft VS2015 is used.
VTK Widgets can be built. But when QT designer loads vtk widgets. A window named "vtkOutputWindow" pops out with error messages:

Generic Warning: In D:\VTK-7.1.1\Source\Rendering\Context2D\vtkContextDevice2D.cxx, line 27
Error: no override found for 'vtkContextDevice2D'.

I noticed that there was someone submitted a pull-request (#616 
 ) about fixing this issue but those commits lead to link error while building vtk widgets just as JCFR replied.

**Comment by altaybrusan** [comment] 2017-11-03 15:13
@tatafarewell Can I ask how did you compile for VTK7? I check vtk core in cmake-gui but when it compile it fails.

**Comment by jcfr** [comment] 2017-11-03 15:28
Hi @altaybrusan , 

Could you indicate which version of VTK your download and which options you are using ?

I recommend to following instructions similar to these ones:

on linux:

```
git clone git://github.com/kitware/vtk
mkdir VTK-Release
cd VTK-Release
cmake -DQt5_DIR:PATH=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt -DCMAKE_BUILD_TYPE:STRING=Release -DVTK_Group_Qt:BOOL=ON ../VTK
cmake --build . --config Release  -- -j5 # or make -j5
```

If you are using Visual Studio, these would be:

from Git Bash:

```
git clone git://github.com/kitware/vtk
mkdir VTK-Release
cd VTK-Release
```

then from a regular command line terminal:

```
cd /path/to/VTK-Relase
cmake -G "Visual Studio 14 2015" -DQt5_DIR:PATH=/path/to/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt -DVTK_Group_Qt:BOOL=ON ../VTK
cmake --build . --config Release -- /m
```

**Comment by jcfr** [comment] 2018-06-04 00:43
Closing. Most likely a duplicate of #777 and  #768

To summarize: a newer version of Qt should be used.

**Closed by jcfr** 2018-06-04 00:43 UTC
