### ISSUE TITLE
File import via ctkDICOMIndexer seems to copy always 

### ISSUE THREAD

**Issue by nolden** [commontk/CTK#104] opened 2011-11-18 22:58 UTC
It should not copy by default, only if the user selected the copy option in the import dialog of ctkDICOMAppWidget (or something similar in an application)

**Comment by jcfr** [comment] 2017-08-28 06:27
@pieper @nolden @fedorov @lassoan  @nolden 

Considering the issue is quite hold and the DICOM infrastructure in DCMTK, CTK and Slicer  went through a lot of improvements, I am closing this issue.

Please, if you think the issue is still current, consider opening a new issue (referencing this one if it is relevant)

**Closed by jcfr** 2017-08-28 06:27 UTC
Labels: Bug, DICOM
