### ISSUE TITLE
modalitiesInStudy not read correctly and more Modality related issues

### ISSUE THREAD

**Issue by toromand** [commontk/CTK#15] opened 2011-04-27 11:29 UTC
1. in CTK/Libs/DICOM/Core/ctkDICOMDatabase.cpp
   the tag DCM_ModalitiesInStudy is not read correctly
   Instead of:
   dataset->findAndGetOFString(DCM_ModalitiesInStudy, modalitiesInStudy);
   it should be:
   dataset->findAndGetOFStringArray(DCM_ModalitiesInStudy, modalitiesInStudy);
   to allow reading multiple modalities (XX\YY\ZZ)
2. Also, you might consider more "standard" way of performing the query with the modalities filter. Although the fact that many SCP implement search by the ModalitiesInStudy tag, it is not according to the DICOM standard and is rather a IHE extension with undefined behavior when used as a search criterion (well, it works well with dcm4chee). So it might now work with all DICOM compliant SCPs. The "proper" way (according to DICOM specifications) would be to perform a query for all needed modalities and combine the results.
3. Rather more important issue is that the current database design lacks a VERY important thing. In DICOM, modalities are part of Series, not the Study, and the ModalitiesInStudy is "informative" and new feature that you should use on Study level for information on the Study, but in your current implementation, you don't have the information on the actual modality of every series. This is a very important information and it is missing although it exists in the dataset. So at present with (1) not fixed you get for study with 2 modalities (XA\OT)

STUDY (XA)
- SERIES 1
- SERIES 2

instead of

STUDY (XA\OT)  -----> *with (1) fixed
- SERIES 1 (XA)
- SERIES 2 (OT)

Regards
Dragan Toroman

**Comment by jcfr** [comment] 2017-08-28 06:26
@pieper @nolden @fedorov @lassoan  @trabs @nolden 

Considering the issue is quite hold and the DICOM infrastructure in DCMTK, CTK and Slicer  went through a lot of improvements, I am closing this issue.

Please, if you think the issue is still current, consider opening a new issue (referencing this one if it is relevant)

cc: @toromand

**Closed by jcfr** 2017-08-28 06:26 UTC
Labels: DICOM
