### ISSUE TITLE
The application randomly crashes at launch time 

### ISSUE THREAD

**Issue by ppacch** [commontk/CTK#668] opened 2016-09-13 11:53 UTC
Hello,

CTK Version: 20160623-master 
Qt: 4.8.6
OS: Windows 7 32 and 64 bits

We have recently updated one of our application using CTK (from a very old CTK version).  We are using only two libraries: Core and PluginFramework.
The update has gone smoothly but now when we launch the application (from time to time) the application crashes with the following error(s):

**system exception: ctkRuntimeException: Not a directory: C:/Program Files/GENESE Tools/300/Edition/configuration
system exception: ctkRuntimeException: Not a directory:** 

Or:

C:/Users/pacchioni/.commontk/97960702/configuration
system exception: ctkPluginDatabaseException: Could not open database. unable to open database file Error opening database

We noted that (as opposed to the previous version where the "internal" sqlite db were only created where the binary is located under the %APPNAME%_ctkpluginfw directory)  CTK uses (randomly?) either the %USER%/.commontk/ID/ or the directory where the binary is installed plus "configuration" (program file or program file x86 in our case).

Have you ready noticed this behavior? If so could you please give some hints?
The randomness of the error makes the debugging pretty hard and following the code we were not able to find something interesting since at the end the Qt SqlDatabase::open method is called.

PS: We don't have any proprietary properties file ... 

Thanks and Regards,
Pierre.

**Comment by pieper** [comment] 2016-09-13 12:11
Hi Pierre - 

I haven't noticed anything like this in Slicer.  We use the ctkDICOM code and it uses the sqlite databases.

Do you have a way to reproduce this using ctk test programs and apps?

Sounds like it could be something related to loading a plugin that was compiled with different settings...?

-Steve

**Comment by ppacch** [comment] 2016-09-13 13:07
Thanks Steve for your quick answer.
I forgot, we also reproduced the problem without any plugin installed (just the main application).
As far as I can see the ctkPluginFrameworkContext::init() method calls the 
storage = new ctkPluginStorageSQL(this); which in turn calls the ctkPluginStorageSQL::open() method where the errors are located, such as:

  if (!database.isOpen())
  {
    if (!database.open())
    {
      close();
      throw ctkPluginDatabaseException(QString("Could not open database. ") + database.lastError().text(),
                                    ctkPluginDatabaseException::DB_SQL_ERROR);
    }
  }

I can try to provide an simple but as I wrote the problem is completely random sometime we launch the application 30 times without any problem and sometime the problem arises 2 or 3 times in the row. 
We also port the application to linux and run under valgrind without any error. Really strange and annoying ... 
Thanks and regards,
Pierre.

**Comment by pieper** [comment] 2016-09-13 13:33
Very odd indeed.  Did you try different versions of Qt?

**Comment by ppacch** [comment] 2016-09-13 13:54
Yes it is under way with Qt 5.7 but for the current project we won't be able to migrate to another Qt version. I'll keep you inform if we found something interesting.

**Comment by ppacch** [comment] 2016-09-13 14:17
Just for information.
A priori the problem doesn't occur with Qt 5.7 (but I can't be sure). Interesting enough with Qt 5.7 the sqlite database is ALWAYS created under the
C:\Users\pacchioni\.commontk\ID\configuration directory.
which, as I wrote previously, it is not the case with Qt 4.8.7 where the sqlite database is created under .commontk or where the exe is installed (randomly?)
We are (almost) lost here ...

**Comment by pieper** [comment] 2016-09-13 15:22
Maybe @saschazelzer or @nolden has some suggestions?  I'm not familiar with the inner workings of the PluginFramework...

**Comment by nolden** [comment] 2016-09-13 18:34
Without being able to look at any code myself at the moment: I suspect Qt4 and Qt5 are using different default locations for application-specific or user-specific data on windows. The directory may also have changed, so if you updated from a much older CTK version, it's possible this directory also changed. You mention

system exception: ctkRuntimeException: Not a directory: C:/Program Files/GENESE Tools/300/Edition/configuration

Did the older version of the application run on the same machine with the same user? Could be some outdated sqlite then that is still lying around.

Are you running this as an installed application? Are the permissions ok? And since it's below "C:/Program Files" and appearing randomly, maybe some antivirus is blocking write access there? Very wild guess though. Maybe @saschazelzer has a more concrete idea where to look for problems?



On 09/13/2016 05:22 PM, Steve Pieper wrote:

Maybe @saschazelzer<https://github.com/saschazelzer> or @nolden<https://github.com/nolden> has some suggestions? I'm not familiar with the inner workings of the PluginFramework...

**Comment by ppacch** [comment] 2016-09-14 08:38
Further investigations showed  that the problem was also here with previous version. It just occurs less often. We also found a way to reproduce the error. A simple main with the following instructions:

QSafeApplication app(argc, argv);
...
ctkProperties props;
props.insert(ctkPluginConstants::FRAMEWORK_STORAGE_CLEAN, 
                    ctkPluginConstants::FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT);

ctkPluginFrameworkFactory fmkFactory(props);
QSharedPointer<ctkPluginFramework> fmk = fmkFactory.getFramework();
Q_CHECK_PTR(fmk.data());
fmk->init();

kc390::edit::QEditWindow mainWindow(*fmk.data()); // our main Qt widget 
mainWindow.show(); 
retcode = app.exec(); // main loop 

1/ launch the application 
2/ quit the application
3/ go (with Microsoft Explorer) to the KC390-Edit_ctkpluginfw just enter to this directory
4/ Relaunch the application -> crash with either the:
system exception: ctkRuntimeException: Not a directory: .../GENESE Edition Tool 300/KC390-Edit_ctkpluginfw
OR the 
system exception: ctkPluginDatabaseException: Could not open database. unable to open database file Error opening database

We also noted that the behavior changes if the application is installed on Program Files (86) or not.

What we did to try to "solve the problem"

redo:
        ctkPluginFrameworkFactory fmkFactory(props);
        QSharedPointer<ctkPluginFramework> fmk;

        try {           
            fmk = fmkFactory.getFramework();
            Q_CHECK_PTR(fmk.data());
            fmk->init();
        }
        catch(...)
        {
            if (trial < 3) {
                Poco::Thread::sleep(500);
                trial ++;
                goto redo;
            }
            else {
                throw Poco::ApplicationException("Cannot initialize CTK framework");
            }
        }
        kc390::edit::QEditWindow mainWindow(*fmk.data());

Not sure it's really academic but seems to solve the problem ...

Don't hesitate to come back to me if you hjave any idea,
Thanks

**Comment by pieper** [comment] 2016-09-14 12:37
Weird... something unique to windows I guess.  I think Marco was right that
this could be related to antivirus or something similar.

**Comment by ppacch** [comment] 2016-09-14 12:44
Yes I can't reproduce the pb on Linux and I share the same opinion but difficult to "prove"  ... 
Thanks for your help,

**Comment by saschazelzer** [comment] 2016-09-15 06:03
At this point, it is really hard to tell what's going on.

The logic for deriving a  location for user configuration data  (e.g for the sqlite database) starts with checking if it can write in the "install area" (the path where the application executable resides). If the current user cannot write to this directory, it checks the "user area" which was initialized with the return value of `QDir::homePath()` (which itself has logic for falling back to different locations).

If something on your system is sporadically blocking write access to one of these locations, you might get different results. Using a debug build of your application should print out more detailed information of what"s going on.

You can also pre-set locations used by the framework manually, by setting framework properties to particular values. E.g. to specify a fixed configuration area, use the `PROP_CONFIG_AREA_DEFAULT` framework property.

**Comment by ppacch** [comment] 2016-09-15 13:08
Thanks for your feedback. We cannot easily change the configuration area in our case but I'll have a look at this possibility.

**Comment by jcfr** [comment] 2016-09-17 03:13
Hi,

Is this reproducible on other Windows workstation ?

Jc

**Comment by jcfr** [comment] 2016-09-17 03:13
Re reading the thread, you mentioned 32 and 64. Does this mean 32 and 64
bit builds on the same machine ?

What about debug vs Release build ?

On Sep 16, 2016 10:52 PM, wrote:

Hi,

Is this reproducible on other Windows workstation ?

Jc

On Sep 15, 2016 9:08 AM, "ppacch" <notifications@github.com> wrote:

Thanks for your feedback. We cannot easily change the configuration area in
our case but I'll have a look at this possibility.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/commontk/CTK/issues/668#issuecomment-247323115>, or mute
the thread

**Comment by jcfr** [comment] 2017-10-10 04:54
@ppacch Did you end up solving the problem ? 

If you still have some issues, do no hesitate to create a new issue. In the mean time, I am closing this one.

**Closed by jcfr** 2017-10-10 04:54 UTC

**Comment by ppacch** [comment] 2017-10-10 06:38
Hello,
Thanks for the follow-up.
Yes we found a "way" to fix this problem - not really academic but it works.

        // workaround for TT#74. From time to time the program crashes at startup
        // 
redo:
        ctkPluginFrameworkFactory fmkFactory(props);
        QSharedPointer<ctkPluginFramework> fmk;

        try {
            
            fmk = fmkFactory.getFramework();
            Q_CHECK_PTR(fmk.data());
            fmk->init();
        }
        catch(...)
        {
            if (trial < 3) {
                Poco::Thread::sleep(500);
                trial ++;
                goto redo;
            }
            else {
                throw Poco::ApplicationException("Cannot initialize CTK framework");
            }
        }
        kc390::edit::QEditWindow mainWindow(*fmk.data());
