### ISSUE TITLE
Having more instances of ctk.ctkDICOMBrowser() messes with signals 

### ISSUE THREAD

**Issue by che85** [commontk/CTK#744] opened 2017-08-24 16:13 UTC
Studies/Series only gets updated upon patient selection for the latest created ctkDICOMBrowser. When selecting another patient in an earlier instance, neither Studies nor Series list gets updated.

The following code reproduces the problem: 

```
import ctk
dicomBrowser = ctk.ctkDICOMBrowser()
dicomBrowser.show()

dicomBrowser1 = ctk.ctkDICOMBrowser()
dicomBrowser1.show()

dicomBrowser2 = ctk.ctkDICOMBrowser()
dicomBrowser2.show()
```

Expected behavior only in `dicomBrowser2`

**Comment by pieper** [comment] 2017-08-24 16:31
Yes, I can replicate this.  Did you look into why this happens yet?

**Comment by che85** [comment] 2017-08-24 16:32
No I haven't looked into that. I only noticed it because we were using another instance within QuantitativeReporting which messed up the original SlicerDicomBrowser.

**Comment by pieper** [comment] 2017-08-24 16:40
There are messages in the log:

QSqlDatabasePrivate::removeDatabase: connection 'DICOM-DB' is still in use,
all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name 'DICOM-DB', old
connection removed.
QSqlDatabasePrivate::removeDatabase: connection 'DICOM-DBTagCache' is still
in use, all queries will cease to work.
QSqlDatabasePrivate::addDatabase: duplicate connection name
'DICOM-DBTagCache', old connection removed.

I recall there might be issues with multiple simulaneous connectsion to the
sqlite db.  Here's where the connection gets set:

https://github.com/commontk/CTK/blob/04607d0ea7fbab104ede38c7c2acc7b5dd1fdfa0/Libs/DICOM/Core/ctkDICOMDatabase.h#L95-L107

https://github.com/commontk/CTK/blob/master/Libs/DICOM/Core/ctkDICOMDatabase.cpp#L290-L333

Which uses:

http://doc.qt.io/qt-5/qsqldatabase.html#addDatabase

**Comment by lassoan** [comment] 2017-08-24 18:20
SQLite should be able to handle any  number of simultaneous connections. Maybe the problem is that each connection must have a unique name.

**Comment by pieper** [comment] 2017-08-24 19:16
Yes, I think a unique name is what is needed.  As I recall you can have multiple connections but maybe not in different threads (which wouldn't be a problem the way we use it).

**Comment by che85** [comment] 2017-09-12 21:07
Is there any progress regarding this issue?

**Comment by lassoan** [comment] 2017-09-13 00:23
Generating a unique connection name seems to fix the problem for me. I've submitted a pull request with the change (https://github.com/commontk/CTK/pull/748). @che85 Could you test it to make sure it solves your problem?

**Comment by jcfr** [comment] 2017-10-10 04:41
Closing. This issue was fixed by Andras pull request

**Closed by jcfr** 2017-10-10 04:41 UTC
