### ISSUE TITLE
Retrieve (and Database) bugs

### ISSUE THREAD

**Issue by toromand** [commontk/CTK#16] opened 2011-05-03 10:12 UTC
- The network connection in ctkDICOMRetrieve is never "dropped". Consequent calls to the retrieve function ends up with the message that "The network address is already in use" as the association is never closed.
  Should include call to closeAssociation on several places. It would be even better to use the member SCU (narked as to-do) in the source, to make it even better. Special care should be taken on exception when called from "outside".
- Retrieved object are written to the disk two times. The portion of code "borrowed" from the dcmdjpeg example should not exist in the retrieve code, because the data (according to the design) should be and is written in the database.insert().
- Also, in ctkDICOMDatabase, there is a problem with retrieved object paths/filenames. The present system of using UIDs is not compliant with the DICOM standard, especially if you would like to create (proper) DICOMDIR and archive media. Paths and filenames should be generated to have max 8 characters according to the DICOM standard (check with Clunie if you don't beleive me :) )
- Different behavior of in-memory and file database should not be implemented (at least not like that) in the Core library code. One should expect that the call to a function (insert()) should depend on parameters only.
- You should also correct the calls to database.insert() to reflect the needed use.
  For instance, in ctkDICOMQuery, the call to database.insert() is missing "false, false" (causing some side-efects, like trying to generate thumbnails for non-existent images)

Enough for this post :)
Keep the good work,
Dragan Toroman

**Comment by jcfr** [comment] 2017-08-28 06:25
@pieper @nolden @fedorov @lassoan  Considering the issue is quite hold and the DICOM infrastructure in Slicer&CTK went through a lot of improvements, I am closing this issue.

Please, if you think the issue is still current, consider opening a new issue (referencing this one if it is relevant)

cc: @toromand

**Closed by jcfr** 2017-08-28 06:25 UTC
Labels: Bug, DICOM
