### ISSUE TITLE
Is there any document for CTK? The official link can't be opened

### ISSUE THREAD

**Issue by softempire** [commontk/CTK#937] opened 2020-10-11 02:44 UTC
https://commontk.org/docs/html/modules.html

**Comment by jcfr** [comment] 2021-02-09 20:12
Thanks for the note and our apology for following only now.

Website https://commontk.org/ is up and running

I reached out to our sysadmin and I will follow up when I hear back.

**Comment by che85** [comment] 2022-05-06 21:37
Seems that this is still the case. Is there any other documentation available?

**Comment by PaulMartinMurphy** [comment] 2023-03-04 03:43
I saw this thread after submitting another issue.

**Comment by lassoan** [comment] 2023-03-04 03:48
Although documentation can be easily generated locally (and it just exposes .h file contents anyway) it would still be nice to be able to browse the documentation online.

**Comment by jamesobutler** [comment] 2023-04-06 01:32
Closing this as a duplicate of https://github.com/commontk/CTK/issues/919

**Closed by jamesobutler** 2023-04-06 01:32 UTC
